
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/robledo/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.10-76060610-generic - x86_64
...
